### ISSUE TITLE
Missing Team Charter

### ISSUE THREAD

**Issue by adavis46** [umwrit350sp17/Team-4#2]
Please commit Team Charter to this repository. Recommend putting it in /team_docs folder (read these [instructions](https://github.com/blog/1436-moving-and-renaming-files-on-GitHub) for creating a folder in a repository).

Assigning to Luke per Progress Report for week 6.

**Comment by lukespencer** [comment]
I submitted the team charter, I have no idea where it is. Same issue right now with the Progress Report, I'll submit and upload it, but it won't appear on the team page.

**Comment by adavis46** [comment]
Both files were submitted as pull requests. I committed them and merged the new branches. Make sure when you create a new file to commit it to the master branch (rather than creating a pull request). Pull requests create new branches of the project that have to be merged; only do that if you have a specific reason to do so.
